name: update
on:
    schedule:
        - cron: '*/30 * * * *' 
    watch:
        types: [started]
    workflow_dispatch:

permissions:
    contents: write

concurrency:
    group: news-update
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: 'Setup nodejs'
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
            - name: 'Install requirements'
              run: |
                  npm ci
            - name: 'Working'
              run: node update.js
            - name: Commit files
              run: |
                  git config --local user.email "dr_hamilton@foxmail.com"
                  git config --local user.name "Ravello-H"
                  git add -A
                  if git diff --cached --quiet; then
                    echo "No files changed."
                  else
                    git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
                    git push origin HEAD:main
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
